version: "3.8"

# Services
services:
  # Frontend - Static Files
  frontend:
    build: ./src/frontend
    ports:
      - 3000:80
    depends_on:
      - api_gateway
    networks:
      - network-frontend

  # API Gateway - Connects the frontend to the backend service
  api_gateway:
    build: ./src/api_gateway/
    ports:
      - 4000:8000
    environment:
      - KONG_NGINX_HTTP_LOG_FORMAT=log_correlation_id '$$remote_addr $$http_x_request_id $$remote_user [$$time_local] \"$$request\" $$status $$body_bytes_sent \"$$http_referer\" \"$$http_user_agent\" Correlation-ID=\"$$http_Correlation_ID\"'
      - KONG_PROXY_ACCESS_LOG=/dev/stdout log_correlation_id
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout log_correlation_id
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    depends_on:
      - backend
    networks:
      - network-frontend
      - network-backend

  # Backend service - The API
  backend:
    build: ./src/backend
    ports:
      - 8000:4000
    networks:
      - network-backend

networks:
  network-frontend:
  network-backend:
